### ISSUE TITLE
Ajouter un champ "Auteurs" (texte libre) au niveau du Parcours

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#150]
Ajouter un champ "Auteurs"  (texte libre) au niveau du Parcours

(et/ou collaborateurs? cf système de licence adopté par CC) 

Demande JJQ/Nac du 27/05

**Comment by taniamcnamara** [comment]
Champs Auteur et Licence au niveau Ressource a priori annoncés par CC pour la Release Candidate de mai 2015
Vérifier si cela inclut bien aussi la Ressource Parcours.

**Comment by Elorfin** [comment]
Champ disponible sur toutes les ressources.

Disponible en production suite à l'installation de Claroline v5 du 02/07/2015.
