### ISSUE TITLE
Harmoniser la position et les libellés des boutons d'action, comme Valider/OK, Modifier/Editer ou Annuler (tantôt à droite, tantôt à gauche…)

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#153]
Harmoniser la position et les libellés des boutons d'action, comme Valider/OK, Modifier/Editer ou Annuler (tantôt à droite, tantôt à gauche…)

cf doc JJQ du 11/6

**Comment by taniamcnamara** [comment]
@chalonn Nathalie, je t'invite à ajouter un commentaire ici dès que tu détectes une incohérence ergonomique dans l'ENPA

**Comment by taniamcnamara** [comment]
Besoin reconfirmé par CC (Flavia Himmel etc) lors du premier hangout "usages/ergo" CC du 30/6/15 et fonctionnement du chantier transerve en discussion (next hangout 28/7/15)

**Comment by Elorfin** [comment]
Je cloture car la demande existe déjà au niveau de Claroline.
