### ISSUE TITLE
Player : Problème dans l’affichage d'image: se comporte comme une visionneuse d’images 

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#172]
Problème dans l’affichage d'image: si cette image est située dans un répertoire avec d’autres images, le conteneur ressource image se comporte comme une visionneuse d’images (il y a des flèches indésirables "suivante/précédente" et on peut voir les autres images située dans le répertoire comme une diaporama, y compris celles supprimées de l'étape)

**Comment by pitrackster** [comment]
Pull request mergé par CC (https://github.com/claroline/CoreBundle/pull/871)

**Comment by Elorfin** [comment]
Disponible dans Claroline 4. Il faudra donc attendre la prochaine mise en production pour avoir le fix.

**Comment by Elorfin** [comment]
Disponible en production suite à l'installation de Claroline v5 du 02/07/2015.
