### ISSUE TITLE
Dans l’éditeur de texte,  pourvoir intégrer une ressource texte, son ou vidéo sans avoir à taper son code

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#185]
Dans l’éditeur de texte,  pourvoir intégrer une ressource texte, son ou vidéo sans avoir à taper son code

**Comment by chalonn** [comment]
Dans l'éditeur texte de la description d'une étape, on aimerait avoir les mêmes outils dans lorsque l'on crée une ressource texte (voir copie d'écran ci-dessous) bouton "tous les outils" que l'on déplie et accès à "insérer une ressource existante" ainsi que" télécharger un fichier depuis l'ordinateur".
Plus globalement il faudrait que tous les éditeurs texte sur l'ENPA soient harmonisés (ressource texte, collecticiel, commentaires dans le collecticiel)
![image](https://cloud.githubusercontent.com/assets/9264291/5999741/2c30ec46-aad5-11e4-81e0-ece487eafcfa.png)

![image](https://cloud.githubusercontent.com/assets/9264291/5999748/38e4b85a-aad5-11e4-93c7-d13903968e5d.png)

**Comment by Elorfin** [comment]
Duplicate #278.

**Comment by Elorfin** [comment]
Duplicate #277.
