### ISSUE TITLE
Bouton "compléter ma production " et "sauvegarder et terminer" non explicites → Voir doc CR évolution érgonomique (plugins)

### ISSUE THREAD

**Issue by purplefish32** [InnovaLangues/ENPA#19]
Bouton "compléter ma production " et "sauvegarder et terminer" non explicites → Voir doc CR évolution érgonomique (plugins) => à changer respectivement en "reprendre mon travail" et en "enregistrer et soumettre pour évaluation" (vu avec NaC)

**Comment by taniamcnamara** [comment]
Réouvert pour test du Collecticiel V1 de JUIN 2015 suite à la réunion Collecticiel avec NC du 26/2/15

**Comment by purplefish32** [comment]
Cette issue n'est plus pertinente.
