### ISSUE TITLE
Donner la possibilité de créer un événement sur une journée entière (pour l’instant, nous sommes obligés de mettre une heure de fin et de début)

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#200]
Donner la possibilité de créer un événement sur une journée entière (pour l’instant, nous sommes obligés de mettre une heure de fin et de début)

cf doc ENPA NAC p16-17 (mars 2014)

**Comment by taniamcnamara** [comment]
Possibilité de soumettre cette issue à CC?

**Comment by Elorfin** [comment]
Disponible en production suite à l'installation de Claroline v5 du 02/07/2015.
