### ISSUE TITLE
connexion et inscription devraient être inversés dans la liste (ordre de priorité)

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#202]
connexion et inscription devraient être inversés dans la liste (ordre de priorité)
pour septembre désactivation de l'inscription claroline, donc demande à traiter d'ici la future réactivation (SEP 2015 a priori) d'où P2 = Année 3.

**Comment by Elorfin** [comment]
Du coup quel est l'ordre attendu ? (que je puisses vérifier dans Claroline si c'est OK ou pas)

*Login
*Register

**OU**

*Register
*Login

???

**Comment by taniamcnamara** [comment]
(voir ausi l'issue 1204 du CoreBundle)

**Comment by Elorfin** [comment]
Les deux boutons sont maintenant l'un à côté de l'autre. Ce ticket n'a donc plus de sens pour Claroline v5.

Disponible en production suite à l'installation de Claroline v5 du 02/07/2015.
