### ISSUE TITLE
outil utilisateur : tout le monde a des droits

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#210]
Lorsqu'un collaborateur voit les utilisateurs d'une formation, il peut les supprimer (en cliquant sur la croix à droite de leur rôle affecté ex : toto ======>gestionnaireX)
Le collaborateur peut aussi inscrire de nouveaux utilisateurs via le bouton ad hoc.
C'est problématique, pour l'instant on paramètre les formations pour ne pas donner accès à cet outil mais dans des formations hybrides il faudrait que les utilisateurs se "voient".

**Comment by taniamcnamara** [comment]
Merci de prévoir d'affecter un développeur objectif JUIN 2015

**Comment by taniamcnamara** [comment]
CC annonce le mode lecture seule dans le user management d'un workspace, pour la Release Candidate de mai 2015. A prévoir de retester donc.

**Comment by Elorfin** [comment]
Disponible en production suite à l'installation de Claroline v5 du 02/07/2015.
