### ISSUE TITLE
Les ressources complémentaires sont affichées/héritées dans des étapes qui n'ont pas de lien entre elles 

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#219]
Des ressources complémentaires s'affichent là où elles ne devraient pas s'afficher (elles sont héritées par des étapes parallèles et non enfants) 
Dans l'exemple donné : http://enpa.innovalangues.net/innova_path/workspaces/101/tool/path/edit/93#/panel-secondary-resources
les livrets de liaison devraient s'afficher uniquement dans l'étape voulue (livret 1 dabns étape 1, livret 2 dan sétape 2, livret 3 dans étape 3 etc) d'ailleurs c'est ce que nous montre l'éditeur de parcours (vue-etape-editeur) mais au final on a livret 1= étape 1 livret 2 dans étape 1 et 2, livret 3 dans étape 1, 2 et 3 etc (voir image vue-etape-player.jpg)

**Comment by Elorfin** [comment]
@arnaudbey : tant que tu y es est-ce que tu pourras reporter ton fix dans le branche 3.x stp ?
