### ISSUE TITLE
problème d'affichage des ressources web dans les parcours

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#221]
Dans les étapes, les ressources web s'affichent dans un frame dont la hauteur n'est pas suffisante pour assurer un confort de lecture.
![integration-ress-web-parcours](https://cloud.githubusercontent.com/assets/9264291/4914092/44082a90-64bd-11e4-8d69-5b85ca204b4e.png)

**Comment by taniamcnamara** [comment]
Si c'est "en cours" il faut un "assigned" qui est dessus svp?

**Comment by taniamcnamara** [comment]
@purplefish32  merci de mettre un assigned ou enlever "en cours" mais de préférence affecter ce P1

**Comment by Elorfin** [comment]
sauf, si il y a un assigned différent, tu peux considérer que tous les tickets concernant l'ENPA & Parcours me sont assigné par défaut.

**Comment by taniamcnamara** [comment]
Décicion réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM): le P1 pour juin consiste en une solution de contournement temporaire qui est de fixer une hauteur fixe à décider en testant avec Nathalie, ce n'est pas LA solution au problème (problème connu, général et complexe) mais un workaround

**Comment by Elorfin** [comment]
Disponible en production suite à l'installation de Claroline v5 du 02/07/2015.
