### ISSUE TITLE
Message d'erreur après publication d'un parcours dupliqué

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#224]
J'ai dupliqué le parcours en route vers le B2 parcours PASS! anglais sur l'instance eval.enpa, la duplication s'est bien passée mais lorsque j'ai modifié le titre du parcours dupliqué et que j'ai voulu publier les modifications, j'ai obtenu un message d'erreur :
An exception occurred while executing 'INSERT INTO claro_resource_rights (mask, role_id, resourceNode_id) VALUES (?, ?, ?)' with params [1, 15, 1527]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1527-15' for key 'resource_rights_unique_resource_role' 
ceci ne m'empêche pas de voir le parcours avec les modifications néanmoins
adresse du parcours :http://eval.innovalangues.net/innova_path/workspace/6/path/178/step/1729
merci.

**Comment by Elorfin** [comment]
Le problème n'étant plus reproduit depuis plus d'un mois sur les dernières versions de l'ENPA, je clôture.
