### ISSUE TITLE
demande de récupération d'un parcours

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#227]
Nous aimerions récupérer le parcours suivant : 
http://enpa.innovalangues.net/innova_path/workspace/386/path/212/step/2863 au 28/11/14 (14h28)
voici ce que l'on a du parcours à présent dans l'éditeur : 
![parcours-deesses](https://cloud.githubusercontent.com/assets/9264291/5414558/4eb3e2ce-8220-11e4-9141-a3bc0911fe97.png)

**Comment by Elorfin** [comment]
Problème corrigé dans le #233.
