### ISSUE TITLE
affichage du sommaire du parcours non disponible

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#229]
Lorsque l'on clique sur le bouton sommaire en haut à droite dans le payer parcours (cf copie écran),on n'affiche pas le sommaire.
![affichage-sommaire](https://cloud.githubusercontent.com/assets/9264291/5666829/d8841198-9762-11e4-93c2-8e6308e598a6.jpg)

**Comment by Elorfin** [comment]
Problème bien constaté.
En fait, il s'avère que le sommaire ne s'affiche même plus lorsqu'on clique sur le bouton.

**Comment by Elorfin** [comment]
Un correctif paretiel est disponible en production et eval.

On peut afficher le sommaire en cliquant sur le bouton correspondant, par contre l'ouverture automatique ne fonctionne toujours pas.

**NB** : l'ouverture fonctionne sur mon environnement local (dev & prod), mais sur les environnement de prod et eval, elle fonctionne uniquement sur les dev.

**Comment by Elorfin** [comment]
Sera annulé par le ticket #242.
