### ISSUE TITLE
affichage incorrect de ressources complémentaires dans player

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#230]
Des ressources complémentaires qui ne sont pas liées à une étape (voir copie éditeur) , s'affichent dans des étapes où elles ne sont pas liées (voir copie player )
copie éditeur :
![ress-compl-editeur](https://cloud.githubusercontent.com/assets/9264291/5670925/a0833824-9784-11e4-9899-721e204a67e7.jpg)
copie player :
![ress-compl-player](https://cloud.githubusercontent.com/assets/9264291/5670939/b4aacd6c-9784-11e4-973f-8659020ebf96.jpg)
adresse du parcours : http://enpa.innovalangues.net/innova_path/workspace/662/path/262/step/5708

**Comment by Elorfin** [comment]
Duplicate #219
