### ISSUE TITLE
Impossible d'afficher le paramétrage des outils des nouvelles formations créées (depuis la mise à jour du 5/01/15))

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#232]
Je reporte le bug que j'avais déjà annoncé, voici un lien vers un espace test où on constate cela : http://enpa.innovalangues.net/innova_path/workspace/662/path/262/step/5708
paramètres>outils
http://enpa.innovalangues.net/workspaces/tool/properties/664/tools

**Comment by Elorfin** [comment]
Ce problème est corrigé en prod et eval.

Petit point sur le fonctionnement des droits des outils :
- Certains outils sont vérouillés et sont accessibles uniquement par les administrateurs (dans la matrice, tu as un "-" à la place des boutons) et ne sont donc pas configurables par les utilisateurs

- De même certains outils ne sont pas accessibles par les personnes non logguées sur la plateforme. Pour un utilisateur, il n'est donc pas possible de modifier la visibilité de ces outils pour les utilisateurs anonymes (idem, il y a un "-").

J'ai testé avec un étudiant, j'ai réussi à lui donner accès à l'outils Parcours.

**Attention** : étant donné que le système de droit a été modifié, vous allez devoir repasser sur toutes vos formations pour positionner les droits comme vous le voulez.

**Comment by chalonn** [comment]
entendu, merci
