### ISSUE TITLE
Problème d'encodage à la sauvegarde du Parcours

### ISSUE THREAD

**Issue by Elorfin** [InnovaLangues/ENPA#233]
Lors de la sauvegarde du Parcours, les caractères spéciaux ne sont pas correctement encodés, ce qui aboutit à un plantage complet de l'éditeur (pas d'initialisation d'Angular).

Cependant, la publication du Parcours corrige ce problème d'encodage en mettant à jour la structure (voir en quoi les 2 méthodes divergent). Ceci peut donc être utilisé comme solution de secours jusqu'à ce que le correctif soit disponible en production.

Pour le moment ce problème se pose uniquement sur le parcours de grec (id = 212).

**Comment by Elorfin** [comment]
@chalonn : c'est votre problème sur le Parcours "Le jugement des déesses".

**Comment by chalonn** [comment]
le problème s'est posé sur un autre parcours (PAA en italien) aujourd'hui 12/01/15 entre 15h30 et 16h30 : http://enpa.innovalangues.net/innova_path/workspace/17/path/33/step/1925
lors de la sauvegarde on a une page blanche pas de confirmation de sauvegarde puis on revient sur la  liste des parcours, on publie et c'est bon.

**Comment by Elorfin** [comment]
@chalonn : avez-vous réessayé et avez-vous reproduit le problème ? Si non, puis-je faire quelques tests dans la journée sur le PAA Italien ou le Grec ?

**Comment by Elorfin** [comment]
Le problème est corrigé.
Disponible en production et eval (v2.4.11).
