### ISSUE TITLE
La modification d'un lien dans la description d'une étape n'est pas prise en compte

### ISSUE THREAD

**Issue by Elorfin** [InnovaLangues/ENPA#234]
Si on modifie uniquement l'url d'un lien dans le TinyMCE d'une étape, la modification n'est pas reportée dans le modèle AngularJS, si aucune autre modification n'a été faite dans le texte.

**NB** : Si le bug se trouve dans le plugin TinyMCE ou dans le plugin AngularJS pour TinyMCE, c'est grave la loose !

**Comment by taniamcnamara** [comment]
Qqch peut-il être fait pour juin? Sinon merci de repasser en P2 et éventuellement en XC

**Comment by Elorfin** [comment]
Réparé.
Disponible dans la version 5.2.4 de PathBundle.
Sera livré lors de la mise à jour de septembre.
