### ISSUE TITLE
Créer "un accordéon" dans l'éditeur de parcours au niveau de l'affichage des étapes

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#236]
Pour des raisons d'ergonomie dans la saisie, il faudrait que l'on puisse plier/réduire les étapes sur lesquelles on ne travaille pas car lorsque les parcours sont longs (cf  PAA italien niveau B2.1) on a beaucoup de mal à descendre et remonter pour sauvegarder.

**Comment by Elorfin** [comment]
L'accordéon a été développé pour l'éditeur.
Comme il est question de revoir le player, je n'ai pas mis la fonctionnalité dans le sommaire pour le moment.

**Comment by taniamcnamara** [comment]
Ce plier/déplier des étapes dans l'éditeur pourra être dans la release de juin?

**Comment by Elorfin** [comment]
C'est ce qui est prévu. Pas avant car, il nécessite l'installation d'un Claroline 4 (il faut donc une mise à jour majeure de la plateforme).

**Comment by Elorfin** [comment]
Disponible en production suite à l'installation de Claroline v5 du 02/07/2015.
