### ISSUE TITLE
Création de dossiers non désirés lors de la copie des Parcours

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#237]
après utilisation de la fonction copie de parcours, on obtient des dossiers non désirés et impossible à supprimer.
adresse du workspace (voir dossiers ressources)
http://enpa.innovalangues.net/workspaces/390/open/tool/home

**Comment by Elorfin** [comment]
La création du dossier est en effet un bug.
En ce qui concerne la suppression, tu ne peux pas supprimer car il y a au moins une ressource qui est utilisée dans un Parcours.

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM): Modèles et duplication = P2

**Comment by Elorfin** [comment]
Disponible en v6
