### ISSUE TITLE
Lenteur de publication/republication des parcours volumineux

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#239]
le problème est là aussi connu, je le note simplement.
Voici une formation où on rencontre le pb : http://enpa.innovalangues.net/workspaces/17/open/tool/innova_path
![image](https://cloud.githubusercontent.com/assets/9264291/5999499/979378c6-aad2-11e4-8737-32163fdc39a0.png)

**Comment by chalonn** [comment]
je pense qu elors du bureau du 3/02/15 il faudrait que l'on estime la complexité

**Comment by arnaudbey** [comment]
On a peut-être une solution là, qui permet de diviser le temps de publication par 5 voire 10 (sur les gros parcours) mais y'a encore quelques tests à faire

edit : plutôt par 2 que par 10

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM) : pas de solution logicielle simple identifiée à ce jour, des solutions infra existent (augmenter RAM et CPU) mais rien n'est décidé dans l'immédiat si ce n'est prévenir les utilisateurs de cette lenteur (qui techniquement se justifie). Voir s'il est possible de ne pas concevoir de parcours trop volumineux (les découper?...) => boucler ce qu'il y a boucler pour juin et sinon on repasse ce ticket en P2

**Comment by Elorfin** [comment]
Les dernières modifications sur Parcours ont permis d'améliorer légèrement les performances.
La suppression de la notion d'Activité dans Claroline permettra également d'obtenir de meilleurs performances.
