### ISSUE TITLE
Orthographe tableau de bord (il manque un S à resSources)

### ISSUE THREAD

**Issue by purplefish32** [InnovaLangues/ENPA#240]
Une petite coquille dans le tableau de bord. le "taux d'utilisation des resources", il manque un S à resSources.

**Comment by eldoniel** [comment]
Ref : https://github.com/claroline/CoreBundle/pull/1022

**Comment by eldoniel** [comment]
Réparé, en attente de claroline

**Comment by Elorfin** [comment]
Disponible en v6
