### ISSUE TITLE
Ajouter une configuration pour masquer le fil d'ariane du Player

### ISSUE THREAD

**Issue by Elorfin** [InnovaLangues/ENPA#241]

**Comment by taniamcnamara** [comment]
Sauf erreur de ma part, cette demande provient de Flavia de CC n'est-ce-pas? Peut-être attendre une validation BE avant de se lancer

**Comment by chalonn** [comment]
on va avoir une réunion sur ces pbs d'ergonomie.

**Comment by taniamcnamara** [comment]
(Suite à une relance de Laurent Gruber de CC pour la Release Candidate de mai 2015, on a déjà une validation écrite de D Kesler, à moi de voir si cela suffit au niveau du BE...)

**Comment by Elorfin** [comment]
Disponible en production suite à l'installation de Claroline v5 du 02/07/2015.
