### ISSUE TITLE
Mettre le sommaire du Player dans une sidebar au lieu d'une modale

### ISSUE THREAD

**Issue by Elorfin** [InnovaLangues/ENPA#242]
@taniamcnamara : tu pourrais me confirmer que cette demande a été validée stp (il semblerait que oui, mais dans le doute...) ?

**Comment by chalonn** [comment]
je te réponds car tania n'est pas là ce n'est pas encore validé mais ça devrait l'être sous peu. On te tient au courant.

**Comment by Elorfin** [comment]
OK, standby dans ce cas jusqu'à validation.

**Comment by taniamcnamara** [comment]
Ok pour standby, mais à repasser en P1 (car pas trop de sens d'être standby ET bloquant)

**Comment by taniamcnamara** [comment]
@chalonn Ce P1 est-il bien confirmé et à faire pour juin?

**Comment by taniamcnamara** [comment]
oui: #269 #270

**Comment by Elorfin** [comment]
Duplicate #269
