### ISSUE TITLE
impossible de couper/coller plus de deux ou trois ressources

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#244]
Avoir la possibilité de couper/coller ou copier/coller plus de deux ou trois ressources.
voir sur : http://enpa.innovalangues.net/workspaces/104/open/tool/resource_manager#resources/1090
message d'erreur obtenu : quand on souhaite couper/coller ou copier/coller plus de deux ou trois ressources "Une erreur s'est produite. Veuillez contacter l'administrateur"

**Comment by taniamcnamara** [comment]
Merci d'évaluer la complexité et/ou d'affecter à CC

**Comment by Elorfin** [comment]
Bug connu. claroline/Claroline#651

**Comment by Elorfin** [comment]
Disponible en production suite à l'installation de Claroline v5 du 02/07/2015.
