### ISSUE TITLE
Affichage incorrect de l'empreinte dans le fil d'Ariane

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#245]
il s'agit d'un bug relevé par Flavia et Guillaume aussi ;  quand je ferme un parcours et que je l'ouvre à nouveau, l'empreinte affiche la dernière étape mais pas tout le chemin parcouru  pour arriver à cette étape.
![empreinte](https://cloud.githubusercontent.com/assets/9264291/6132056/6383354c-b150-11e4-9ec5-131b76985cd9.png)

**Comment by taniamcnamara** [comment]
https://github.com/InnovaLangues/PathBundle/issues/167

**Comment by taniamcnamara** [comment]
je croise avec le 167 au cas où cela ait un rapport

**Comment by taniamcnamara** [comment]
Merci d'évaluer la complexité

**Comment by taniamcnamara** [comment]
Demande réitérée ainsi par JJQ/NC dans
cf NOTE_ERGONOMIE_ENPA1-5.pdf section 1.3:

Fil d’Ariane – Empreinte/retour en arrière : Correction des dysfonctionnements : Afficher le chemin complet de navigation jusqu’à la dernière étape vue, ne pas afficher seulement la dernière étape :
- Quand on ferme le parcours et qu’on l’ouvre à nouveau
- Quand on remonte dans l’arborescence.

**Comment by arnaudbey** [comment]
Petit rappel, dans le cas où l'on remonte dans l'arborescence, il se peut qu'on ne puisse pas afficher le chemin complet de l'étape précédente pour la simple raison que le chemin de l'étape actuelle n'est pas systématiquement un sous-chemin du chemin l'étape précédente. Donc, à moins d'afficher un chemin non réalisable, on ne peut pas faire grand chose pour ça. La fonctionnalité demandée est pour ainsi dire "bancale", et la réalisation ne peut pas en corriger les imperfections.

**Comment by arnaudbey** [comment]
Le fil d'Ariane n'est pas amené à disparaitre de toute façon ?

**Comment by taniamcnamara** [comment]
Non pas que je sache. De petites retouches sont prévues du type remplacer "Suite" par "..." et assortir les couleurs (cf ERGO ENPA V1.5 sous Informatique>Suivi des demandes>Docs de ref).
CC nous a demandé la possibilité de le masquer (en cours de négo) mais JJQ n'a nulle intention de le masquer. Des flèches Etape Précédente/Etape Suivante ont été demandées:
- par CC dans toutes les étapes du sommaire (à la place du fil)
- par JJQ uniquement d'une soeur à l'autre d'une même Suite d'activités (en plus du fil)
  La question n'est pas encore totalement tranchée (perso je ne vois pas d'inconvéniant de permettre le cas 1 si c'est si attendu par les autres utilisateurs de CC)...

**Comment by taniamcnamara** [comment]
@arnaudbey hello Arnaud, pourrais-tu fournir un exemple d'incohérence? merci

**Comment by arnaudbey** [comment]
par exemple, si on est sur _Parcours  > Semaine1 > Activité 4_ et qu'on va sur _Parcours > Semaine 2_ on ne peut pas afficher l'ancien chemin en superposition du premier. On peut l'afficher seulement si on ajoute _Semaine 1 > Activité 4_   au chemin courant ce qui donne _Parcours > Semaine 2 > Semaine 1 > Activité 4_. On pourrait lui enlever _Semaine 2_ mais du coup le lien serait trompeur (il pointe vers la semaine 2 mais il a l'air de pointer vers la semaine 1)

En fait à partir du moment où on bifurque vers une étape dont un des parents est un frère d'un des parents de l'étape initiale il y a ce souci

**Comment by chalonn** [comment]
Bonjour,
je réagis à la remarque de Arnaud et je constate qu'il y a une déconnexion certaine entre les demandes de développement et les réactions de l'équipe informatique, non le fil d'ariane ne doit pas disparaitre, pour claroline peut-être mais pas pour Innovalangue il ne faut pas croire que même si les développement sont fait sous la manche ils doivent s'appliquer à nous.

**Comment by taniamcnamara** [comment]
Il me semble qu'un bon compromis dans l'immédiat serait: pouvoir paramétrer SOIT les flèches SOIT le fil, et que cela soit 100% transparent pour JJQ, ainsi tout le monde est satisfait, qu'en pensez-vous? En juin avec la Suite, on pourra réintroduire les flèches (soit uniquement pour les soeurs d'une Suite si JJQ est contre de les afficher partout, soit partout pour tous les steps si cela ne gêne pas).

**Comment by taniamcnamara** [comment]
@arnaudbey Merci pour l'exemple. Dans ce cas pour l'emprunte, ne peut-on pas garder en grisé tous les niveaux précédemment visités uniquement dans les cas où cela fait du sens, et réinitialiser à vide lorsque l'on repart dans un nouveau sous-chemin?

**Comment by Elorfin** [comment]
La discussion est en train de déraper.
Merci de revenir au sujet initial du ticket qui est le système d'historique dans le fils d'ariane.

Les flèches de navigation d'une étape à l'autre et la disparition (via configuration) du fils d'ariane n'ont que peu de rapport avec le sujet qui nous intéresse.

@taniamcnamara : l'intérêt de cette solution est très limité, car cela veut dire qu'on aura un historique très limité (seulement, quelques étapes) et dans ce cas, des boutons de navigation "étape suivante/précédente" est amplement suffisant.

La solution la plus viable (et qui a déjà fait ses preuves) en terme d'historique est un bouton "historique" dans la sidebar du sommaire qui permet l'affichage complet (depuis qu'il est entré sur le Parcours et réinitialisé lorsqu'il le quitte puis revient) de l'historique de toutes les étapes visitées (liste affichée dans la sidebar à la place du sommaire).

**Comment by Elorfin** [comment]
@chalonn : le ticket qui parle du masquage du fil d'ariane est ici : #241. On ne fait pas les choses "sous la manche".

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM) : dans ce cas en P1 supprimer totalement le backtrack grisé en attendant de trouver d'autres solutions plus complètes

**Comment by Elorfin** [comment]
Disponible en production avec l'installation de Claroline v5 du 02/07/2015.
