### ISSUE TITLE
Parcours perdu/planté sur demo.innovalangues.net

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#246]
![bug-demo](https://cloud.githubusercontent.com/assets/9264291/6134624/f7361d10-b162-11e4-85d9-379453f0a408.png)
http://demo.innovalangues.net/workspaces/12/open/tool/innova_path

erreur reportée par JJQ le 10/02/15

**Comment by taniamcnamara** [comment]
ai rajouté "planté" dans le titre, les données ne sont peut-être pas perdues

**Comment by taniamcnamara** [comment]
Je mets M par défaut: merci de réévaluer la complexité

**Comment by taniamcnamara** [comment]
demo = instance instable et temporaire pour tests ponctuels uniquement (on attend la Release Candidate plus stable de CC annoncée pour mai 2015)

**Comment by taniamcnamara** [comment]
A priori ce ticket pourra être annulé la semaine du 8 juin 2015 lors de l'upgrade de Démo avec CC V5
