### ISSUE TITLE
Nommage des modèles de parcours

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#247]
un ou plusieurs modèles peuvent avoir le même nom, prévoir au minimum un nommage automatique avec un suffixe (1), (2) etc...voire proposer à l'utilisateur de renommer son parcours si nom identique à un autre modèle existant.

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM): Modèles = P2
