### ISSUE TITLE
problème de navigation retour  entre deux questions (exerciseur) dans un parcours

### ISSUE THREAD

**Issue by chalonn** [InnovaLangues/ENPA#248]
il faudrait revoir le bouton retour entre deux questions dans un parcours :
![bouton_retour](https://cloud.githubusercontent.com/assets/9264291/6336478/2fcf361c-bba3-11e4-96ea-a26020f65b28.png)

Si l'utilisateur clique sur le bouton "Retour"  :
 il accède à une page bloquée (s'il n'a pas accès aux ressources)
![page_bloquee](https://cloud.githubusercontent.com/assets/9264291/6336502/4e4844ee-bba3-11e4-88d3-9c1b1019417e.png)
ou il accède aux ressources :
![ressources](https://cloud.githubusercontent.com/assets/9264291/6336556/b2888be4-bba3-11e4-8609-80295be25adc.png)

**Comment by taniamcnamara** [comment]
A déterminer: problème lié au bouton Retour de l'exerciseur (non-Innova) ou bien au PathBundle? Ou bien à la config des droits?
Si bug du PathBundle, merci d'évaluer la complexité (je mets M en attendant)

**Comment by Elorfin** [comment]
Corrigé en v6.
