### ISSUE TITLE
Intégration d'un plugin TinyMCE pour améliorer la lisibilité du HTML généré

### ISSUE THREAD

**Issue by purplefish32** [InnovaLangues/ENPA#249]
Je propose d'installer un plugin codemirror dans TinyMCE pour bénéficier de la coloration de syntaxe, l'auto-indentation et le "code linting" dans tout nos sous bundles qui ne s'appuy pas sur le TinyMCE du core CC (Parcours, Editeur d'activité...)

Ref : https://github.com/claroline/CoreBundle/issues/1038

**Comment by taniamcnamara** [comment]
Qqch peut-il être fait pour juin si c'est S? Sinon merci de repasser en P2 et augmenter la complexité

**Comment by Elorfin** [comment]
Intégré dans le TinyMCE de Claroline.
Disponible en v6.
