### ISSUE TITLE
Gérer le collecticiel comme une ressource CC

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#250]
Gérer le collecticiel comme une ressource CC 
(cf mail JJQ du 23/2/15)

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by ericvincenterv** [comment]
Nous sommes partis du bundle ICAP/DropZone où leur DropZone était une ressource CC.

**Comment by taniamcnamara** [comment]
Cette ressource devra donc être associable à une étape, soit en tant que principale, soit en tant que complémentaire. Navigation et ouvertures des onglets à tester.
Pour la V1:
Pour l'apprenant le titre de la page/onglet qui s'ouvre en premier sera  "Collecticiel - Vue Apprenant"
Pour l'enseignant le titre de la page/onglet qui s'ouvre en premier sera  "Collecticiel - Vue Enseignant"
(faut-il 2 Ressouces CC différentes ou uniquement jouer sur les droits à voir...)

**Comment by ericvincenterv** [comment]
Il faut faire un point sur cette issue afin d'être le plus clair possible en positionnant concrétement les souhaits sur un support papier ou autre. Merci.

**Comment by chalonn** [comment]
il faut envisager l'entrée dans le collecticiel par le gestionnaire de ressources, mais c'est la même chose.Le gestionnaire crée le collecticiel qui n'est pas là par défaut comme l'agenda comme une ressource CC, il a forcement un premier formulaire qui n'a rien à voir puis paramétrage et vue en lecture ou écriture.

**Comment by ericvincenterv** [comment]
D'après ce que l'on a vu lors de notre réunion il y a 10 jours, on entre bien dans le collecticiel par le gestionnaire de ressources.
Je vais prendre en compte : 
"
Pour l'apprenant le titre de la page/onglet qui s'ouvre en premier sera "Collecticiel - Vue Apprenant"
Pour l'enseignant le titre de la page/onglet qui s'ouvre en premier sera "Collecticiel - Vue Enseignant"
"

**Comment by taniamcnamara** [comment]
Merci, à noter que ces libellés ne sont pas forcément 100% définitifs dans leur titrage, mais le principe fonctionnel y est et on y verra clair pour les tests

**Comment by ericvincenterv** [comment]
Pour les libellés (et j'évoque strictement les libellés), si le travail en soit n'est pas long, il est effectivement important pour la compréhension des utilisateurs.
A noter qu'il est tout de même préférable de regrouper le plus possible les demandes de changement de libellés.

**Comment by ericvincenterv** [comment]
@taniamcnamara a écrit : 
"Pour la V1:
Pour l'apprenant le titre de la page/onglet qui s'ouvre en premier sera "Collecticiel - Vue Apprenant"
Pour l'enseignant le titre de la page/onglet qui s'ouvre en premier sera "Collecticiel - Vue Enseignant"
"
![250](https://cloud.githubusercontent.com/assets/5363344/7413500/c425d596-ef4c-11e4-953a-8e31925f9bac.png)
![250-2](https://cloud.githubusercontent.com/assets/5363344/7413508/c6ee6c7a-ef4c-11e4-9334-c93680e63f6e.png)

**Comment by purplefish32** [comment]
Fait
