### ISSUE TITLE
Pouvoir affecter une durée (début/fin) à un collecticiel (cf DropZone)

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#251]
Pouvoir affecter une durée (début/fin) à un collecticiel (cf DropZone)
cf mail JJQ du 23/2/15
Merci de spécifier la complexité

**Comment by ericvincenterv** [comment]
La notion de date existait dans le DropZone. Ceci a été gardé pour le collecticiel Innova. A tester.

**Comment by ericvincenterv** [comment]
Sur le collecticiel de l'ICAP, les dates sont ainsi : 
![date](https://cloud.githubusercontent.com/assets/5363344/6980697/4d36e7ba-d9f6-11e4-9f3d-a6ccfe3bf9c2.png)

Quelles sont les modifications à apporter pour le collecticiel ?

**Comment by chalonn** [comment]
la notion de collecticiel fini n'existe pas par contre la notion d'accès ou pas est compatible pour moi il faut laisser les possibilités (sauf évaluation par les pairs qui sera vue plus tard).

**Comment by chalonn** [comment]
par dates est une option (donc pas forcement activé) par contre par défaut le collecticiel doit être ouvert.

**Comment by ericvincenterv** [comment]
Je vais donc enlever la partie de l'évaluation par les pairs au niveau des dates.
Pour la reste, je ne change rien.
On est d'accord ?

**Comment by taniamcnamara** [comment]
Il faut peut-être aussi masquer Valider automatiquement... et Nombre de corrections... => je redirige vers Nathalie

**Comment by chalonn** [comment]
oui je pense qu'il faut l'enlever à ce stade (la partie de l'évaluation par les pairs au niveau des dates.)
Pour ce qui est de la validation automatique, on est plus dans ce cas de figure puisque maintenant c'est l'étudiant qui fait la demande de correction par le biais d'une deamnde de commentaire (qui équivaut à la soumission du document pour évaluation, je ne sais pas si cette fonctionnalité est conservée même si elle est détournée) je me souviens que l'on avait dit que de toutes façons si l'éudiant pour une raison ou pour une autre ne demandait pas de correction, l'enseignant voyait qd même les travaux déposés.
Pour ce qui est du nbre de corrections il faut le masquer.

**Comment by taniamcnamara** [comment]
Confirmé: il ne reste donc pour la V1 que l'option de gérer des dates (optionnel donc) avec date et heure de début et date et heure de fin.
Dans la section juste au-dessus = option manuelle, où il y a 5 options, il faut également masquer la 3e et la 4e et ne garder que les 3 autres, avec la 2 sélectionnée par défaut.

**Comment by ericvincenterv** [comment]
La 3ème est : Les apprenants peuvent corriger les copies (Evaluation par les pairs).
La 4ème est : Les apprenants peuvent rendre leur copie ET peuvent corriger les copies (Evaluation par les pairs).
Il doit rester : 
L'évaluation n'a pas encore commencé.
Les apprenants peuvent rendre leur copie.
L'évaluation est terminée. Plus personne ne peut y participer.

**Comment by ericvincenterv** [comment]
Je suis arrivé à ce résultat : 
![251](https://cloud.githubusercontent.com/assets/5363344/7139749/3a0acdca-e2c8-11e4-8ce9-996a18946b50.png)

Je vais modifier le texte situé en dessous de "Planification"

**Comment by ericvincenterv** [comment]
L'état à ce jour : 

![251-2](https://cloud.githubusercontent.com/assets/5363344/7158166/7eea8610-e377-11e4-8934-affcbe6448fd.png)

Dans l'attente de vos retours.

**Comment by taniamcnamara** [comment]
OK pour moi, Nathalie à confirmer.
A renommer: "Les apprenants peuvent soumettre leurs travaux."

**Comment by chalonn** [comment]
ok pour moi.

**Comment by ericvincenterv** [comment]
L'état à ce jour : 
![251-3](https://cloud.githubusercontent.com/assets/5363344/7407403/e0f146dc-ef11-11e4-95a6-73051b6539c5.png)

**Comment by taniamcnamara** [comment]
Très bien, il reste à masquer Nombre de corrections... (cf + haut)
(et ignorer les contrôles liés à ce champ)

**Comment by ericvincenterv** [comment]
L'état : 
![251-4](https://cloud.githubusercontent.com/assets/5363344/7409569/a8638030-ef27-11e4-8ef1-23c59ff3a85d.png)

Question : 
j'enlève également les 2 dernières lignes ?

**Comment by purplefish32** [comment]
Dans la version V1, tous ces champs ont été masqués et leurs valeurs ne sont plus utilisées.
