### ISSUE TITLE
Collecticiel: Permettre à l'enseignant évaluateur de saisir une consigne facultative (ou plusieurs), type commentaire riche

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#252]
Permettre à l'enseignant évaluateur de saisir une consigne facultative (ou plusieurs), type commentaire riche
cf mail JJQ du 23/2/15
Merci de spécifier la complexité

**Comment by ericvincenterv** [comment]
Il y a les notions de critère et d'instruction. La notion de consigne correspond à quoi ?

**Comment by taniamcnamara** [comment]
Instruction est à renommer en Consigne (dans le suivi des demandes xls, il y a une ancienne demande écrite à ce sujet). Tout du moins à l'affichage. Pour critère on va se renseigner.

**Comment by taniamcnamara** [comment]
#85

**Comment by taniamcnamara** [comment]
@chalonn Nathalie, que doit devenir la notion de "Critère" du DropZone dont parle Eric dans le nouveau Collecticiel? Merci

**Comment by chalonn** [comment]
c'est ok pour la notion de critère qui demeure.
Pour la notion d'instruction, celle-ci  n'est valable que si un concepteur enseignant donne son formulaire à un correcteur autre que lui (cas de la correction par les pairs) pour  moi étant donné qu'on n'utilise pas la correction par les pairs on peut masquer ce champ texte.

**Comment by taniamcnamara** [comment]
Ce n'est donc pas une "Consigne" au sens consigne pour l'apprenant?

**Comment by ericvincenterv** [comment]
En masquant la partie indiquée par Nathalie, nous obtenons ceci : 

![252](https://cloud.githubusercontent.com/assets/5363344/7023631/f81f66fa-dd36-11e4-8d0d-5f42e75411a3.png)

Est-ce correct ?

**Comment by chalonn** [comment]
il ne faudrait pas qu'il y ait "vous pouvez proposer une zone de commentaire libre au correcteur" puisque la notion de correcteur autre que soit n'existe pas (en tous cas pas dans cette V1)

**Comment by ericvincenterv** [comment]
@chalonn : pour la zone "vous pouvez proposer une zone de commentaire libre au correcteur", j'enlève le texte ET la zone à cocher ? Quid de la zone "Rendre le commentaire obligatoire" ?

**Comment by taniamcnamara** [comment]
Confirmé: il faut masquer toute la section Critères d'évaluation et TOUJOURS proposer une zone de commentaire par défaut et NE JAMAIS le rendre obligatoire. D'où inutile d'avoir ces infos à l'écran.

**Comment by taniamcnamara** [comment]
Précision: il serait intéressant que l'enseignant puisse saisir une ou plusieurs consignes, avec le même mécanisme et la même ergonomie que pour saisir un ou plusieurs commentaires en cours d'évaluation.

**Comment by taniamcnamara** [comment]
Tout comme les 0 à N fichiers génériques associés, ces consignes seront alors visibles dans toutes les vues apprenants dans le premier pavé correspondant aux commentaires-consignes et/ou fichiers génériques de l'enseignant, en lecture seule pour l'apprenant.

**Comment by taniamcnamara** [comment]
Juste pour rappel les 3 pavés de la vue Apprenant sont
1) Consignes-commentaires et/ou fichiers génériques partagés par l'enseignant
2) Commentaires et/ou fichiers spécifiques adressés par l'enseignant nominativement à l'apprenant X
3) Fichiers avec ou sans commentaire(s) déposés par l'apprenant et potentiellement évaluables

**Comment by taniamcnamara** [comment]
Pour l'enseignant, la saisie des consignes et/ou fichiers génériques, doit se faire dans un onglet différent de Paramètres, qu'on nommera "Consignes" et dont le titre de la page sera Consignes et fichiers génériques (en remplacement de la section 'Instruction' sous Paramètres du DropZone)

**Comment by ericvincenterv** [comment]
Fait : 
"Confirmé: il faut masquer toute la section Critères d'évaluation et TOUJOURS proposer une zone de commentaire par défaut et NE JAMAIS le rendre obligatoire. D'où inutile d'avoir ces infos à l'écran." 

![252-2](https://cloud.githubusercontent.com/assets/5363344/7159388/13d47132-e382-11e4-8f38-86a6234aed67.png)

**Comment by purplefish32** [comment]
En ce qui concerne la version V1, je considère ce ticket fait. 1 Seule consigne.
