### ISSUE TITLE
Permettre à l'enseignant évaluateur de déposer 0 à N fichiers génériques "Enseignant", visibles dans toutes les vues Apprenant du collecticiel

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#253]
```
Permettre à l'enseignant évaluateur de déposer un ou plusieurs fichiers d'amorce (ou zéro, facultatif) en guise de consigne/travail  ou document-modèle etc. Ces fichiers génériques "Enseignant" doivent être visibles dans toutes les vues Apprenant du collecticiel
```

cf mail JJQ du 23/2/15
Merci de spécifier la complexité

**Comment by ericvincenterv** [comment]
Quelle la notion de fichier "Amorce" ? 
Nous avons les types de documents suivants ;
fichier téléchargé
zone de texte libre
ressources
liens web

**Comment by taniamcnamara** [comment]
Amorce est une notion pédagogique, pas technique. Cela signifie document à compléter. C'est donc la première version d'un devoir plus complet à rendre, comme un modèle/Template. Comme on a prévu de ne gérer le versioning que manuellement en s'appuyant sur le nommage, pas d'inquiétude, c'est juste un premier fichier que l'enseignant partage avec tous les apprenants. Fichier "générique" c'est pareil. L'apprenant le récupère, le renomme, le complète en tant que devoir à rendre et le rendra dans un second temps.

**Comment by taniamcnamara** [comment]
Suite à ces précisions, merci d'attribuer une complexité

**Comment by ericvincenterv** [comment]
@taniamcnamara : ce n'est pas ce que l'on obtient en cliquant sur "Téléchargement" ici ?

![253](https://cloud.githubusercontent.com/assets/5363344/7025337/4a210236-dd43-11e4-8a37-a605490f078f.png)

Sinon, venir me voir pour ce point.

**Comment by taniamcnamara** [comment]
#252

**Comment by taniamcnamara** [comment]
Comme pour les 0 à N consignes saisies par l'enseignant, les fichiers génériques déposés par l'enseignant seront visibles dans le premier pavé générique dédié à l'enseignant de toutes les vues apprenants.
Les consignes seront en lecture seule.
Les fichiers génériques seront téléchargeables par l'apprenant (heureusement;o))

Cette zone de saisie de consignes et de dépôts de fichiers génériques, partageables, doit correspondre pour l'enseignant à un onglet différent de l'onglet "Paramètres". On n'est plus en train de paramétrer le collecticiel, mais d'en démarrer un (le travail commence...).
Pour le titre de ce nouvel onglet en V1 je propose "Consignes", en remplacement du paragraphe Instruction qui est pour l'instant dans Paramètres, mais le titre plus complet une fois dans la page sera plutôt: "Consignes et fichiers génériques".

**Comment by taniamcnamara** [comment]
Il faut donc également prévoir pour l'enseignant un onglet lui listant tous les collecticiels apprenants disponibles. A voir si cela peut être combiné ou non avec la liste des demandes d'évaluation (qui serait alors une sous-vue des éléments cochés) ou un onglet différent, sachant que JJQ parle bien de 4 onglets différents pour l'enseignant:
Paramètres
Consignes (et fichiers génériques)
Collecticiels Apprenants (la liste complète nom par nom)
Demandes d'évaluation (fichier par fichier)

**Comment by chalonn** [comment]
actuellement les consignes et les fichiers à ajouter sont dans le même formulaire que les paramètres du collecticiel. pour le titre, je ne sais pas pour fichiers génériques est-ce que générique est un terme que l'on avait choisi ?

**Comment by purplefish32** [comment]
Fait, 
La version V1 comporte les fichiers dans la zone de texte riche.
