### ISSUE TITLE
Pour chaque fichier déposé par l'apprenant, l'apprenant peut indiquer (ex: via une case-à-cocher) qu'il demande une évaluation par l'évaluateur (ou pas). 

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#258]
Pour chaque fichier déposé par l'apprenant, l'apprenant peut indiquer (ex: via une case-à-cocher) qu'il demande une évaluation par l'évaluateur (ou pas). Si coché, c'est donc ce fichier qui devient l'objet de l'évaluation, sinon, il peut par exemple déposer un fichier et un commentaire, sans pour autant demander une évaluation, comme une question sur une image par exemple. Ou tout autre situation intermédiaire.
cf mail JJQ du 23/2/15
merci de spécifier la complexité

**Comment by ericvincenterv** [comment]
Un système de gestion de demande d'évaluation a été mis en place à partir d'un bouton "A valider".
Refaire des tests, notamment au niveau des commentaires.

**Comment by taniamcnamara** [comment]
La demande d'évaluation ne doit pas être nommée "A valider" mais "A évaluer" ou mieux "Demande d'évaluation"

**Comment by ericvincenterv** [comment]
@taniamcnamara : 

voir l'état actuel du développement en prenant en compte ta remarque : 

![258](https://cloud.githubusercontent.com/assets/5363344/7025554/b77007b4-dd44-11e4-9bdb-dd1cb229ba42.png)

**Comment by taniamcnamara** [comment]
Dans l'ensemble du collecticiel, remplacer:
copies par travaux
copie soit par travaux (si le pluriel ne gêne pas) soit par document (si le singulier s'impose)
rendre par soumettre
envoyer par déposer
valider par évaluer (lorsque le sens est le même)
validation par évaluation (idem)

en cas de doute, nous demander.

(et s'assurer que "pair" ou "pairs" n'apparaît plus)

**Comment by ericvincenterv** [comment]
Le fichier de traduction est corrigé.

Pour "et s'assurer que "pair" ou "pairs" n'apparaît plus)", cela se fera au fur et à mesure des tests et du parcours sur le collecticiel.

**Comment by purplefish32** [comment]
Fait
