### ISSUE TITLE
Désactiver (temporairement) l'évaluation par les pairs du DropZone : pour Innova 2015, l'évaluation est faite par l'enseignant évaluateur

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#259]
Désactiver (temporairement) l'évaluation par les pairs du DropZone : pour Innova 2015, l'évaluation est faite par l'enseignant évaluateur
cf réunion collecticiel avec NC du 26/2/16
merci de spécifier la complexité

**Comment by ericvincenterv** [comment]
L'onglet "évaluation par les pairs" a été désactivé. Et l'onglet correspondant à la nouvelle évaluation a été créé.

**Comment by taniamcnamara** [comment]
Il faut donc aussi masquer toutes les occurrences de ce concept qui seraient ailleurs (ex: paramétrage des dates...)

**Comment by purplefish32** [comment]
Fait
