### ISSUE TITLE
Rendre la note sur 20 facultative

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#261]
Rendre la note sur 20 facultative : pour Innova 2015, l'évaluation sera essentiellement un fichier corrigé et/ou un commentaire de l'enseignant évaluateur, voire rien. Seul l'enseignant évaluateur peut mettre une note, et uniquement lorsque l'apprenant a fait une demande d'évaluation

cf reunion Collecticiel avec NC du 26/2/15

merci de sépcifier la complexité

**Comment by ericvincenterv** [comment]
Le travail sur cette partie a été commencé.

**Comment by taniamcnamara** [comment]
La complexité est liée à la gestion des cas (cas avec note vs cas sans note)? Car j'imagine que de la passer de obligatoire à facultative est plutôt simple?

**Comment by taniamcnamara** [comment]
Visiblement dans le DropZone, la note sur 20 n'est pas saisie mais calculée à partir d'une notation basée sur une grille de critères où on sélectionne des radio-boutons. Ne rien changer à cela mais rendre le tout facultatif (et le plus discret possible) au lieu de obligatoire.

On y reviendra ultérieurement car nos échelles d'appréciation sont à creuser.

**Comment by ericvincenterv** [comment]
Zone n'est plus obligatoire : fait.

**Comment by purplefish32** [comment]
Fait
