### ISSUE TITLE
Désactiver la notion de note moyenne globale (cf DropZone)

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#263]
Désactiver la notion de note moyenne globale (cf DropZone)
cf réunion Collecticiel avec NC du 26/2/15
merci de spécifier la complexité

**Comment by taniamcnamara** [comment]
#262

**Comment by ericvincenterv** [comment]
Une fois que le point #262 sera plus clair, ce point le sera également. Ils sont dépendants.

**Comment by taniamcnamara** [comment]
Le besoin pour juin est de désactiver la fonction. Aucune notion de moyenne requise, et c'est du P1

**Comment by taniamcnamara** [comment]
Pour récapituler pour juin, on garde la note sur 20 mais on la rend facultative et on ne calcule aucune moyenne qu'il ne faut plus afficher nulle part pour l'instant

**Comment by taniamcnamara** [comment]
Complexité à revoir? Il faut juste désactiver la moyenne, est-ce si complexe? Il n'est même pas dit qu'on veuille la réintroduire un jour car JJQ est pour l'instant, contre toute notion de moyenne.

**Comment by taniamcnamara** [comment]
(on garde les calculs du DropZone Critères=>Note/20 pour un Apprenant X sans rien toucher, mais on ne calcule ni une moyenne générale par Apprenant, ni une moyenne globale de la classe).

**Comment by purplefish32** [comment]
Fait
