### ISSUE TITLE
	Permettre comme dans le DropZone que les fichiers à déposer puissent correspondre à certains types de ressources CC 

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#265]
Permettre comme dans le DropZone que les fichiers à déposer puissent correspondre à des types de ressources CC (texte, URL, média…) récupérables directement via le Ressource Picker CC au lieu d'un file browser local. Ces types sont pré-définis parmi une liste restreinte de types possibles.

cf réunion Collecticiel avec NC du 26/2/15

merci de spécifier la complexité

**Comment by ericvincenterv** [comment]
Merci de me faire voir un exempe dans le DropZone.

**Comment by purplefish32** [comment]
Fait, La version du collecticiel sur laquelle on a "forké", contenait déjà cette modification.
