### ISSUE TITLE
Player de Parcours : mettre le sommaire dans un menu latéral

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#269]
Sommaire : « side-bar » - Suppression du bouton sommaire initialement placé à gauche du bouton de retour à l’accueil de la formation et remplacement par un système side bar. A gauche de l’écran, ajouter une barre de navigation (« side-bar ») dans laquelle s’affiche le sommaire du parcours. Affichage par défaut du sommaire à l’ouverture d’un parcours depuis et seulement depuis un niveau supérieur au parcours (bureau par exemple). Ainsi, le retour en arrière dans le Fil d’Ariane jusqu’au niveau de l’étape 1 (Parcours) n’entraîne pas de modification dans l’affichage du sommaire (il reste ouvert s’il était ouvert, il reste fermé si il était fermé). Une option telle celle présente dans l’actuel sommaire sera également présente dans ce sommaire side-bar. Mais, au lieu « Ne pas afficher automatiquement », il sera indiqué « Afficher à l’ouverture du parcours ». Cette option sera donc sélectionnée par défaut.

**Comment by taniamcnamara** [comment]
cf NOTE_ERGONOMIE_ENPA1-5.pdf section 1.4

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by taniamcnamara** [comment]
(Conséquences à prévoir:
=> Réduction de la largeur de la zone description de l’étape et ressources principales
=> Déplacement de l’onglet ressources complémentaires)

**Comment by chalonn** [comment]
on pensait à une proportion de 25% pour le sommaire et 75% pour la description est-ce faisable ?

**Comment by Elorfin** [comment]
Disponible en production avec l'installation de Claroline v5 du 02/07/2015.
