### ISSUE TITLE
Sommaire (side bar) : principe ouverture – fermeture => Réduction de la largeur de la zone description de l’étape et ressources principales => Déplacement de l’onglet ressources complémentaires

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#270]
Sommaire (side bar) : principe ouverture – fermeture
=> Réduction de la largeur de la zone description de l’étape et ressources principales
=> Déplacement de l’onglet ressources complémentaires

**Comment by taniamcnamara** [comment]
cf NOTE_ERGONOMIE_ENPA1-5.pdf section 1.4.1

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by taniamcnamara** [comment]
#269

**Comment by Elorfin** [comment]
Duplicate #269
