### ISSUE TITLE
Player de Parcours : Système de marquage des étapes dans le sommaire

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#271]
Ajouter un système de marquage manuel des étapes dans le sommaire du player.

Le marquage peut avoir les valeurs suivantes : 
- A faire (valeur par défaut), 
- Terminé, 
- Important, 
- En cours

Associer pour chaque valeur une icône.

**Comment by taniamcnamara** [comment]
cf NOTE_ERGONOMIE_ENPA1-5.pdf section 1.4.2

Merci de spécifier la complexité

a minima pour juin, faire au moins Terminé Y/N (à recroiser avec demande CC)

**Comment by taniamcnamara** [comment]
#269 
#270

**Comment by taniamcnamara** [comment]
(J'ai donc ajouté "manuel" après marquage puisqu'il existe une autre demande de marquage automatique pour plus tard)

**Comment by taniamcnamara** [comment]
est-ce que même le minima Terminé Y/N manuel est XC?

**Comment by Elorfin** [comment]
le problème c'est pas le nombre valeurs, c'est la mécanique qu'il y a derrière.

**Comment by taniamcnamara** [comment]
(demande reconfirmée par CC à l'ACCU du 7 mai 2015)

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM): marquage MANUEL basé sur une LOV paramétrable (et sans traitement derrière) = confirmé P1 => pour juin 2015

**Comment by taniamcnamara** [comment]
Merci de repasser cette issue en C si effectivement <10JH et sinon laisser en XC

**Comment by Elorfin** [comment]
LOV ? List of Values ?

**Comment by taniamcnamara** [comment]
oui

**Comment by Elorfin** [comment]
OK. Pour plus de clarté, merci d'éviter les abréviations exotiques.

**Comment by Elorfin** [comment]
Disponible en production avec l'installation de Claroline v5 du 02/07/2015.
