### ISSUE TITLE
Flèches situées dans le cadre du titre de l’étape pour passer directement d’une étape soeur à l’autre

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#272]
Navigation rapide d’une étape soeur à sa voisine - Flèches situées dans le cadre du titre de l’étape pour passer directement d’une étape soeur à l’autre sans devoir utiliser le fil d’Ariane (uniquement pour les étapes soeur) 
- Gérer l’activation des flèches en fonction des circonstances (première de la série des étapes soeur => flèche gauche inactive et grisée ; dernière de la série des étapes soeur
  => flèche droite inactive et grisée)

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 1.4.1

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by taniamcnamara** [comment]
#245

**Comment by Elorfin** [comment]
Par contre le #245 n'a rien à voir.

**Comment by taniamcnamara** [comment]
OK mais quel est le ticket où CC demande l'affichage des flèches partout (et ce développement est-il déjà engagé?)

**Comment by taniamcnamara** [comment]
Au final pour juin aura-t-on des flèches uniquement d'une soeur à l'autre (demande JJQ initiale) ou pour toute étape il y aura Précédente et Suivante (demande CC non-contredite par JJQ)?

**Comment by Elorfin** [comment]
Disponible en production avec l'installation de Claroline v5 du 02/07/2015.
