### ISSUE TITLE
Lecture des ressources principales - Problème de frame trop petit notamment pour la lecture des Hot Potatoe

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#273]
Lecture des ressources principales - Problème de frame trop petit notamment pour la lecture des Hot Potatoes : nécessité d’agrandir le frame dans lequel les exercices type Hot Potatoes, les fichiers type ressource web, les ressources type scorm sont lues.

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 1.8

**Comment by taniamcnamara** [comment]
Idem #221 ?

**Comment by Elorfin** [comment]
oui
