### ISSUE TITLE
Possibilité de sauvegarder, publier sans sortir de l’éditeur et en même temps de visualiser le résultat

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#274]
Boutons « sauvegarder », « publier » et « visualiser » - Possibilité de sauvegarder, publier sans sortir de l’éditeur et en même temps de visualiser le résultat : un seul bouton permet ces trois opérations à partir de l’éditeur de parcours. Les boutons « Publier et visualiser », « Sauvegarder » et « Quitter » seront disponibles en haut à droite de l’écran mais aussi en bas à droite.

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 2.1

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by Elorfin** [comment]
Disponible en production avec l'installation de Claroline v5 du 02/07/2015.
