### ISSUE TITLE
Réduction de l’arbre de l’éditeur - Pouvoir réduire l’arbre de l’éditeur grâce à un système d’accordéon 

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#275]
Réduction de l’arbre de l’éditeur - Pouvoir réduire l’arbre de l’éditeur grâce à un système d’accordéon 

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 2.2

NC: fait sur dernière version de Claroline, cf. instance demo

A recroiser avec issue existante?

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité (même si fait)

**Comment by Elorfin** [comment]
Duplicate #236.
