### ISSUE TITLE
Mettre en regard la zone d’édition à droite (description – ressource principale et complémentaire) de manière à éviter de jouer sans cesse avec l'ascenseur

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#276]
Zone d’édition à droite - Mettre en regard la zone d’édition à droite (description – ressource principale et complémentaire) de manière à éviter de jouer sans cesse avec l'ascenseur lorsque l'étape est "basse" (en plus du système d’accordéon de l’arbre de l’éditeur).

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 2.3

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by Elorfin** [comment]
Disponible en production avec l'installation de Claroline v5 du 02/07/2015.
