### ISSUE TITLE
Homogénéisation des éditeurs de texte

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#277]
Homogénéisation des éditeurs de texte - Pour les enseignants concepteurs éditant les ressources, l’éditeur de texte devrait avoir, partout dans l’ENPA (description d’une étape, ressource texte, commentaire dans le collecticiel…), les mêmes boutons et fonctionnalités, se présentant de la même manière. Par exemple, dans l’éditeur de parcours l’éditeur de texte de la description devrait se présenter de la même manière que celui de la description de « Activity » dans l’espace ressources. Par ailleurs et toujours pour exemple, ces éditeurs devraient être identique à ceux que l’on trouve en relation avec les ressources texte dans l’espace des ressources.

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 2.5.1

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité et/ou à voir avec CC?
à recroiser avec issue existante?

**Comment by Elorfin** [comment]
Standby car Claroline a prévu de reprendre tous les TinyMCE. 
On calquera une fois que ce travail sera fait.

**Comment by taniamcnamara** [comment]
Mettre si possible la ref de la issue CC correspondante ici

**Comment by taniamcnamara** [comment]
A retester en CC V5?

**Comment by Elorfin** [comment]
Non pas en v5.
Nous avons traité le problème avec Nicolas Godfraind. Ce sera dans la re-livraison de septembre.

version 5.2.4 de PathBundle.
