### ISSUE TITLE
Permettre, à partir de l’éditeur, d’insérer des images et des vidéos dans le texte, via adresse URL ou « Ajouter » une ressource ou upload d'un fichier

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#278]
Insertion d’images et de vidéo - Permettre, à partir de l’éditeur, d’insérer des images et des vidéos dans le texte, non seulement à partir d’une adresse URL mais également, comme dans l’espace ressources à partir de « Ajouter » (une ressource de l’espace ressources) et « Créer » (+ Importer un fichier à partir de l’ordinateur). En somme, se rapprocher de la logique suivie dans l’espace ressource (en lus de l’URL).

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 2.5.2

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité et/ou voir avec CC?

**Comment by Elorfin** [comment]
Comme vu lors de la réunion que nous avons eu avec Laurent Gruber lorsqu'il est venu nous rendre visite, Claroline a prévu de modifier cette fonctionnalité, afin de la rendre plus intuitive et de passer par les ressources de la plateforme.

**Comment by taniamcnamara** [comment]
Mettre si possible la ref de la issue CC correspondante ici

**Comment by taniamcnamara** [comment]
A retester en CC V5?

**Comment by Elorfin** [comment]
Traité et en production
