### ISSUE TITLE
Supprimer l’outil « Parcours » du volet de navigation (en vue de le remplacer par un widget parcours « évolué »)

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#279]
Supprimer l’outil « Parcours » du volet de navigation (en vue de le remplacer par un widget parcours « évolué »)

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 2.7.2

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by Elorfin** [comment]
Disponible en production avec l'installation de Claroline v5 du 02/07/2015.
