### ISSUE TITLE
widget parcours - Courte description avec nombre maximum de caractères autorisés

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#280]
Nouvelle vue par défaut du widget parcours - Courte description (à côté du Nom du Parcours, inchangé) : comme actuellement mais faire coïncider le nombre maximum de caractères autorisés dans l’éditeur de parcours avec le nombre de caractères effectivement affichés ici
cf schéma 
cf NOTE_ERGONOMIE_ENPA1-5.pdf section 3.2.1

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM):  évo Widget Parcours = P2

**Comment by Elorfin** [comment]
Fait.
A mettre en démo.

**Comment by Elorfin** [comment]
Disponible en v6
