### ISSUE TITLE
widget parcours - Bouton Éditer en fonction des droits

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#282]
Nouvelle vue par défaut du widget parcours - Bouton Éditer : visible en fonction des droits
(cf schéma)
cf NOTE_ERGONOMIE_ENPA1-5.pdf section 3.2.1

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by taniamcnamara** [comment]
#281

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM):  évo Widget Parcours = P2

**Comment by Elorfin** [comment]
Disponible en production avec l'installation de Claroline v5 du 02/07/2015.
