### ISSUE TITLE
widget parcours - Statut : Publié/Non-Publié en fonction des droits

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#283]
Nouvelle vue par défaut du widget parcours - Statut : Publié/Non-Publié,  visible par l’ayant droit
(cf schéma)
cf NOTE_ERGONOMIE_ENPA1-5.pdf section 3.2.1

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by taniamcnamara** [comment]
#281

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM):  évo Widget Parcours = P2

**Comment by Elorfin** [comment]
Le statut du Parcours a été ajouté dans le widget.
A mettre en démo.

**Comment by Elorfin** [comment]
Disponible en v6
