### ISSUE TITLE
Edition du widget Parcours - gérer les catégories

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#285]
Edition du widget Parcours - Catégories :  permettre à l’enseignant créateur de formation de gérer les catégories

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 3.2.2

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

à voir avec CC?

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM):  évo Widget Parcours et catégorisation = P2

**Comment by Elorfin** [comment]
Disponible en v6
