### ISSUE TITLE
Edition du widget Parcours - Catégorie d'un Parcours : permettre à l’enseignant créateur de formation d’affecter un parcours dans une catégorie

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#286]
Edition du widget Parcours - Catégorie d'un Parcours : permettre à l’enseignant créateur de formation d’affecter un parcours dans une catégorie

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 3.2.2

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by taniamcnamara** [comment]
#285

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM):  évo Widget Parcours et catégorisation = P2

**Comment by Elorfin** [comment]
L'utilisation du Bundle Tag de Claroline permet de faire cela depuis le gestionnaire de ressources (la gestion de tous les tags de la plateforme se fait au niveau de l'administration).
Ce bundle est installé en démo et sera installé en production lors du passage en v6.
