### ISSUE TITLE
Edition du widget Parcours - Création/Modification/Publication

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#287]
Edition du widget Parcours - Création/Modification/Publication : pouvoir
- créer un nouveau parcours
- créer à partir d’un modèle existant (au lieu de « Créer à partir d’un modèle »)
- éditer (même fonctionnalités que dans la vue liste du widget)
- publier les parcours qui ne le seraient pas

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 3.2.2

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by taniamcnamara** [comment]
#235

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM):  évo Widget Parcours = P2 => issue à repasser en P2 ou qqch à livrer pour le Path V5?

**Comment by Elorfin** [comment]
Disponible en v6.
(sauf pour la création, impossible techniquement en l'état actuel)
