### ISSUE TITLE
Edition du widget Parcours - pouvoir filtrer l’affichage des parcours par statut ou par catégorie

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#288]
Edition du widget Parcours - pouvoir filtrer l’affichage des parcours : Permettre au créateur de formation et à l’administrateur de n’afficher par exemple que les parcours publiés, que les parcours correspondants à telle ou telle thématique. Cela implique un taggage ou marquage des parcours

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 3.2.3
NB: nécessaire pour Cooplang

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by taniamcnamara** [comment]
#286 
#285 
#287 
#283

**Comment by taniamcnamara** [comment]
#235

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM):  évo Widget Parcours = P2

**Comment by Elorfin** [comment]
Disponible en v6
