### ISSUE TITLE
Changer le libellé du bouton « Créer à partir d’un modèle » par  « Créer à partir d’un modèle existant »

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#289]
Changer le libellé du bouton « Créer à partir d’un modèle » par  « Créer à partir d’un modèle existant »

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 3.2.5

**Comment by taniamcnamara** [comment]
#287

**Comment by Elorfin** [comment]
Sérieusement ?! Pour faire la distinction avec les modèles inexistants ?

Blague mise à part, un libellé de bouton doit être le plus court possible (sans pour autant sacrifier le sens).
Le "existant" n'ajoute rien à la compréhension de ce que fait le bouton (tu utilises forcément un modèle existant pour la création, si tu pars de rien, c'est une création classique), ça va juste alourdir l'interface.

**Comment by taniamcnamara** [comment]
(A vrai dire, j'ai fait la même remarque à Nathalie, je ne comprends pas bien ce besoin...)

**Comment by chalonn** [comment]
c'est Flavia HImmel qui nous a fait part de ce besoin, lelibellé n'était pas significatif selon elle (suite aux tests effectués pour le suivi du Mooc FOLFLE.

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM):  Modèles = P2
