### ISSUE TITLE
Filtrage du widget parcours en fonction des onglets de la formation (ex: filtre sport dans onglet sport...)

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#290]
Filtrage du widget parcours en fonction des onglets de la formation (ex: widget filtré sur sport affiché dans onglet sport, widget filtré sur cuisine affiché dans onglet X...)

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 3.2.4
Exemple de résultat pour l’étudiant: 3 Onglets associés à une dans la formation, dont un onglet texte classique et 2 onglets dans lequel on a placé dans chacun d’eux un widget parcours. Partons de l’exemple d’une formation Cooplang Italien qui dispose de 11 parcours (créés dans cette formation) : On en affiche certains (disons 5), certains dans l’onglet 2, d’autres dans l’onglet 3.

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by taniamcnamara** [comment]
#286 
#288

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM):  évo Widget Parcours = P2

**Comment by Elorfin** [comment]
Comme vu avec l'équipe fonctionnelle, nous n'avons pas moyen de filtrer en fonction de l'onglet dans lequel nous sommes.

Un filtre par tag est possible et sera implémenté.(#285)
