### ISSUE TITLE
Edition d’un parcours depuis l’espace de ressources

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#291]
Edition d’un parcours depuis l’espace de ressources: le clic-droit doit afficher  (dans l'ordre) :
Renommer
Éditer les propriétés
Éditer les droits
Éditer le parcours
Voir le suivi de l’objet
Supprimer

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 4.1

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité
à recroiser avec demande CC?

**Comment by Elorfin** [comment]
Rectification : il n'y a pas de clic droit, il faut cliquer sur la flèche à côté du nom du Parcours afin de faire apparaitre ce menu.

Je n'ai pas la main sur l'ordre d'apparition des items du menu. Cela permet notamment d'avoir le même ordre pour toutes les ressources.

**Comment by Elorfin** [comment]
Disponible en production avec l'installation de Claroline v5 du 02/07/2015.
