### ISSUE TITLE
Export de parcours

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#297]
Dupliquer une formation pour l’importer dans un autre CC - On bénéficie d’un début d’export des formations mais on doit pouvoir dupliquer aussi un ou des parcours avec toutes les étapes. Prévoir un sélecteur de ressources pour choisir les ressources à exporter (toutes ou certaines).

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 5.4
Export de Parcours également demandé par CC

**Comment by taniamcnamara** [comment]
Merci de spécifier la complexité

**Comment by taniamcnamara** [comment]
Décision réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM):  Export Parcours = P2

**Comment by Elorfin** [comment]
Disponible en production pour la rentrée de septembre 2015.
