### ISSUE TITLE
Permettre d’utiliser des modèles de formation mutualisables, on ne peut jusqu’à présent réutiliser que ses propres modèles 

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#299]
Permettre d’utiliser des modèles de formation mutualisables, on ne peut jusqu’à présent réutiliser que ses propres modèles (que l’on a créés via le formulaire de création de formation)

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 5.3

**Comment by taniamcnamara** [comment]
P2 mais à discuter dès à présent avec CC

**Comment by Elorfin** [comment]
Lors de la création d'un modèle, tu peux choisir avec quels Utilisateurs/Groupes tu veux le partager.

Disponible en prodution avec l'installation de Claroline v5 du 02/07/2015.
