### ISSUE TITLE
Problème du lien dans le mail automatique lors de la création d'utilisateur

### ISSUE THREAD

**Issue by AmonAmaaarth** [InnovaLangues/ENPA#300]
Lors de la création d'un nouvel utilisateur, un mail est envoyé avec l'adresse de la plateforme
http://enpa.innovalangues.net/
mais celle-ci ne s'ouvre pas comme il faut (soit protocole http:/// soit pointe vers Zimbra)
On est obligé de copier/coller le texte du lien pour accéder à la plateforme.

**Comment by Elorfin** [comment]
Disponible en production avec l'installation de Claroline v5 du 02/07/2015.
