### ISSUE TITLE
Affichage du statut du Parcours dans l'Editeur

### ISSUE THREAD

**Issue by Elorfin** [InnovaLangues/ENPA#304]
Affichage du statut du Parcours (affiché avant dans la liste des Parcours qui a été supprimée) : 
- Non sauvegardé
- Non publié
- Publié avec modifications en attentes
- Publié

**Comment by taniamcnamara** [comment]
voir aussi #283

**Comment by Elorfin** [comment]
Pas vraiment de rapport avec le ticket pointé, je supprime la référence.

**Comment by taniamcnamara** [comment]
Il n'y avait peut-être pas de rapport technique, mais certainement un rapport fonctionnel. Bref pas grave...

**Comment by Elorfin** [comment]
Il faut utiliser les reférences uniquement si le développement d'un ticket
est directement impacté par un autre ticket.

Parce que le problème, c'est que tu peux trouver des relations fonctionnelles
partout au sein d'un même module (e.g. Parcours), sinon on aurait fait plusieurs modules.

Du coup il va y avoir 10 000 relations entre les tickets et on va perdre l'intérêt des
relations.

**Comment by Elorfin** [comment]
Disponible en production avec l'installation de Claroline v5 du 02/07/2015.
