### ISSUE TITLE
Fil d’Ariane : remplacer "Suite" + flèche par '…' 

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#309]
Fil d’Ariane - Amélioration de l’apparence de la fonction « suite » : remplacer "Suite" + flèche par '…' 

cf NOTE_ERGONOMIE_ENPA1-5.pdf section 1.1

Confirmé P1 XS en réunion ENPA du 28/05/2015 (JJQ, DT, AP, NC, TM)

**Comment by Elorfin** [comment]
Disponible en production avec l'installation de Claroline v5 du 02/07/2015.
