### ISSUE TITLE
Message d'erreur lors de l'import d'utilisateur

### ISSUE THREAD

**Issue by AmonAmaaarth** [InnovaLangues/ENPA#312]
Import de 15 nouveaux utilisateurs : pas de souci.
Import de 20 personnes : erreur suivante
![erreur_import](https://cloud.githubusercontent.com/assets/8793432/10047027/546ec2e8-620c-11e5-8ebc-b9f84261bdbd.JPG)
mais les comptes sont bien crées (jusqu'à 20 à la fois apparemment)

**Comment by Elorfin** [comment]
C'est une erreur dans l'envoie des emails de notification suite à l'inscription. Cela doit être corrigé dans la version du 29/09/2015.

Merci de nous prévenir si le problème persiste ou de clôturer s'il n'y a plus de problème.

**Comment by Elorfin** [comment]
Petite précision: ça plante uniquement à partir de 20 car le mailer accepte un certain nombre d'erreurs avant de planter réellement (tu le vois au "too many errors" dans l'erreur que tu as envoyée). La limite des erreurs qu'accepte notre mailer doit donc se situer entre 15 et 20.

**Comment by AmonAmaaarth** [comment]
Import de 76 étudiants sans soucis.
