### ISSUE TITLE
Changement de l'expéditeur des mails envoyés par l'ENPA

### ISSUE THREAD

**Issue by AmonAmaaarth** [InnovaLangues/ENPA#314]
Les mails envoyés lors des opérations sur l'ENPA (création de compte, mot de passe modifié...) ont désormais noreply@enpa.innovalangues.net comme expéditeur plutôt que le mail support.
Seuls les mails internes ont le login de l'expéditeur d'affiché, la notification de ce même message vers une boite exérieur comporte aussi le "noreply"

**Comment by Elorfin** [comment]
C'est une convention, la plupart des applications qui envoient des notifications opèrent de la même manière. Tu n'es pas sensé répondre à des mails de notifications, d'où le noreply.

**Comment by AmonAmaaarth** [comment]
C'est noté. Et depuis qu'on peut joindre le support sans se connecter, l'expéditeur de ces mails est moins important.
