### ISSUE TITLE
gestion des utilisateurs : lorsqu'on inscrit un utilisateur à un espace d'activité via l'interface d'administration , on ne peut pas le désinscrire de cet espace via cette interface.

### ISSUE THREAD

**Issue by purplefish32** [InnovaLangues/ENPA#47]
gestion des utilisateurs : lorsqu'on inscrit un utilisateur à un espace d'activité via l'interface d'administration , on ne peut pas le désinscrire de cet espace via cette interface.

**Comment by taniamcnamara** [comment]
A retester en CC V5?

**Comment by Elorfin** [comment]
Il est dorénavant possible d'inscrire et de désinscrire les Utilisateurs sans quitter l'espace d'administration.
