### ISSUE TITLE
gestion des utilisateurs : lorsque l'on constitue un groupe, le bouton envoyer un mail envoie un mail à tous les membres du groupe même en sélectionnant un seul utilisateur on ne peut écrire qu'à tous les membres.

### ISSUE THREAD

**Issue by purplefish32** [InnovaLangues/ENPA#50]
gestion des utilisateurs : lorsque l'on constitue un groupe, le bouton envoyer un mail envoie un mail à tous les membres du groupe même en sélectionnant un seul utilisateur on ne peut écrire qu'à tous les membres.

**Comment by pitrackster** [comment]
Non reproduit en production.
