### ISSUE TITLE
Lorsque le collecticiel n’est pas disponible, ajouter un message, selon le cas :  - La période de soumission des travaux est clôturée - La période de soumission des travaux n’est pas encore ouverte

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#81]
Lorsque le collecticiel n’est pas disponible, ajouter un message, selon le cas : 
- La période de soumission des travaux est clôturée
- La période de soumission des travaux n’est pas encore ouverte

**Comment by taniamcnamara** [comment]
Réouvert pour test du Collecticiel V1 de JUIN 2015 suite à la réunion Collecticiel avec NC du 26/2/15

**Comment by purplefish32** [comment]
La version 1 n'a plus de date d'ouverture/fermeture
Cette issue est non pertinante
