### ISSUE TITLE
Traduction Innova: renommer "ajouter un document" en "déposer un fichier" 

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#83]
Traduction Innova: renommer "ajouter un document" en "déposer un fichier"

**Comment by taniamcnamara** [comment]
Réouvert pour test du Collecticiel V1 de JUIN 2015 suite à la réunion Collecticiel avec NC du 26/2/15

**Comment by purplefish32** [comment]
Les libellées ont tous été revus, cette issue n'est plus pertinente.
