### ISSUE TITLE
Traduction Innova: renommer "instruction" en "consigne" 

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#85]
Traduction Innova: renommer "instruction" en "consigne"

**Comment by taniamcnamara** [comment]
Réouvert pour test du Collecticiel V1 de JUIN 2015 suite à la réunion Collecticiel avec NC du 26/2/15

**Comment by purplefish32** [comment]
Les libellées ont tous été revus, cette issue n'est plus pertinente.
