### ISSUE TITLE
Traduction Innova: renommer "vous n'avez pas encore rendu de production" en "vous n'avez aucun travail en cours" 

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#86]
Traduction Innova: renommer "vous n'avez pas encore rendu de production" en "vous n'avez aucun travail en cours"

**Comment by taniamcnamara** [comment]
Réouvert pour test du Collecticiel V1 de JUIN 2015 suite à la réunion Collecticiel avec NC du 26/2/15

**Comment by taniamcnamara** [comment]
NC: à revoir en fonction des tableaux récapitulatifs vue étudiant et enseignant

**Comment by taniamcnamara** [comment]
Ces anciens renommages du DropZone sont-ils automatiquement reportés dans le nouveau Collecticiel Innova ou à refaire?

**Comment by purplefish32** [comment]
Les libellées ont tous été revus, cette issue n'est plus pertinente.
