### ISSUE TITLE
Ajouter une case à cocher à côté d'une tâche pour indiquer si elle est finie ou pas

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/ENPA#92]
Ajouter une case à cocher à côté d'une tâche pour indiquer si elle est finie ou pas

**Comment by taniamcnamara** [comment]
Bonne idée pour la référence croisée CC, merci

**Comment by Elorfin** [comment]
Disponible en production suite à l'installation de Claroline v5 du 02/07/2015.
